Agung dev
agungtriu/YukKuy-CMS pull request #4
Opened 2023-05-11 08:50 UTC by agungtriu

2023-05-11 12:02 UTC, hrswcksono requested changes

2023-05-11 12:02 UTC, hrswcksono commented on server/controllers/AccountController.js
> +          role: "seller",
customer

2023-05-13 03:09 UTC, hrswcksono approved these changes

2023-05-15 01:40 UTC, hrswcksono approved these changes

2023-05-15 01:42 UTC, samudrazulqifli approved these changes

2023-05-15 02:46 UTC, merged